require("sudokid.set")
require("sudokid.lsp")
require("sudokid.packer")
require("sudokid.remap")
require("sudokid.colorscheme")
require("sudokid.quick_esc")
require("sudokid.dap")
require("sudokid.mason")
