require("sudokid.set")
require("sudokid.pack")       -- must come before mason/lsp (plugins need to be on rtp)
require("sudokid.mason")
require("sudokid.lsp")
require("sudokid.remap")
require("sudokid.colorscheme")
require("sudokid.quick_esc")
require("sudokid.dap")
require("sudokid.harpoon")
require("sudokid.user_defined_fn")
require("sudokid.mini")
